// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  javaSidebar: [{ type: "autogenerated", dirName: "java" }],
  springBootSidebar: [{ type: "autogenerated", dirName: "spring-boot" }],
  reactSidebar: [{ type: "autogenerated", dirName: "react" }],
  sqlSidebar: [{ type: "autogenerated", dirName: "sql" }],
};

export default sidebars;
